/**
 * Ports — the daemon's dependency-inversion boundary (plan §1, layer 2).
 *
 * The domain core and pipeline depend on these interfaces, never on Glaze,
 * Electron, or any host. That's what makes the same services runnable from a
 * daemon, a CLI, a test harness, or (later) a Flutter-backed host.
 */

export interface Logger {
  info(msg: string, meta?: unknown): void;
  warn(msg: string, meta?: unknown): void;
  error(msg: string, meta?: unknown): void;
  debug(msg: string, meta?: unknown): void;
}

export interface Clock {
  now(): Date;
  isoNow(): string;
}

export interface Paths {
  vaultRoot(): string;
  rawDir(dateKey: string): string;
  markdownDir(dateKey: string): string;
  dbPath(): string;
  /** Work order 06 §7: irrelevant files preserved under Irrelevant/<date>/. */
  irrelevantDir(dateKey: string): string;
  /** Work order 06 §7: duplicate bytes preserved under Duplicates/<date>/. */
  duplicatesDir(dateKey: string): string;
}

/**
 * The product of a P1 conversion.
 *
 * The converter identity travels WITH the text because regeneration drift is
 * otherwise undetectable: markdown regenerated by a newer anydoc, or by sips
 * instead of Vision OCR, can differ from the text an extraction actually read,
 * and nothing downstream would know.
 */
export interface Conversion {
  /** Canonical markdown v1. */
  markdown: string;
  /** Backend family: 'anydoc' | 'vision-ocr' | 'plaintext'. */
  converter: string;
  /** Backend identity WITH version, e.g. 'anydoc@0.1.6', 'vision-ocr@macOS26.5'. */
  converterVersion: string;
}

/** P1 conversion port. Implemented by anydoc; swappable for OCR or a stub. */
export interface Converter {
  /** Convert a file to canonical markdown v1. Never throws — returns null on failure. */
  toMarkdown(filePath: string, ext: string, password?: string): Promise<Conversion | null>;
}

/** Domain events published on the bus and streamed to clients over SSE. */
export type DomainEvent =
  | { type: "DocumentReceived"; document_id: string; filename: string; sha256: string; at: string }
  | { type: "DocumentDuplicate"; sha256: string; filename: string; existing_document_id: string; at: string }
  | { type: "MarkdownReady"; document_id: string; markdown_path: string; chars: number; at: string }
  | { type: "AnalysisComplete"; document_id: string; extraction_version: number; at: string }
  | { type: "TransactionRecorded"; transaction_id: string; direction: string; amount_minor: number; currency: string | null; at: string }
  | { type: "MatchProposed"; transaction_id: string; document_id: string; score: number; at: string }
  /**
   * A user edit changed the derived value of one or more transactions. The UI
   * applies the edit optimistically and reconciles on this event, so it must
   * name every transaction touched — a document-scope edit can move several.
   */
  | {
      type: "TransactionReResolved";
      transaction_ids: string[];
      document_id: string | null;
      fields: string[];
      at: string;
    }
  | { type: "JobStateChanged"; job_id: number; phase: string; state: string; at: string }
  | { type: "BatchFinished"; processed: number; at: string }
  /** Vault wiped from Settings. Clients should drop cached state and refetch. */
  | { type: "VaultReset"; scope: "ledger" | "factory"; at: string }
  // ── Work order 06 — Intelligent Intake Triage events (§8) ──
  // Each event carries the intake id, source, filename, disposition, reason,
  // hash, matched document id where relevant, path, and timestamp. The Flutter
  // intake feed distinguishes all dispositions rather than showing generic
  // "processed". Emitted in pipeline order: Received → Triaged → (Accepted |
  // Irrelevant | Duplicate | Failed); Restored on user action.
  | {
      type: "IntakeReceived";
      intake_id: number;
      source: string;
      filename: string;
      received_path: string | null;
      at: string;
    }
  | {
      type: "IntakeTriaged";
      intake_id: number;
      source: string;
      filename: string;
      disposition: "accepted" | "irrelevant" | "failed";
      reason_code: string;
      reason: string;
      confidence: "high" | "medium" | "low";
      triage_review: boolean;
      at: string;
    }
  | {
      type: "IntakeAccepted";
      intake_id: number;
      source: string;
      filename: string;
      sha256: string;
      document_id: string;
      canonical_path: string;
      triage_review: boolean;
      at: string;
    }
  | {
      type: "IntakeIrrelevant";
      intake_id: number;
      source: string;
      filename: string;
      sha256: string | null;
      reason_code: string;
      reason: string;
      canonical_path: string;
      at: string;
    }
  | {
      type: "IntakeDuplicate";
      intake_id: number;
      source: string;
      filename: string;
      sha256: string;
      matched_document_id: string;
      canonical_path: string | null;
      at: string;
    }
  | {
      type: "IntakeFailed";
      intake_id: number;
      source: string;
      filename: string;
      reason: string;
      at: string;
    }
  | {
      type: "IntakeRestored";
      intake_id: number;
      source: string;
      filename: string;
      new_disposition: "accepted" | "irrelevant" | "failed";
      document_id: string | null;
      at: string;
    };

export interface EventBus {
  publish(e: DomainEvent): void;
  subscribe(fn: (e: DomainEvent) => void): () => void;
  /** Events published so far this process, newest last. For late subscribers. */
  recent(limit?: number): DomainEvent[];
}

export interface Ports {
  logger: Logger;
  clock: Clock;
  paths: Paths;
  converter: Converter;
  bus: EventBus;
}
